VFS-11629 Improvements to allow multi-provider demo envs

diff --git a/docker/demo-mode/await-demo b/docker/demo-mode/await-demo
--- a/docker/demo-mode/await-demo
+++ b/docker/demo-mode/await-demo
@@ -1,19 +1,20 @@
 #!/bin/bash
 
-# This file is created by onezone.py when the service is ready
-SERVICE_READY_LOCK_FILE='/root/service-ready.lock'
-
 # Optional first argument
 TIMEOUT=${1:-300}
 
+await-demo-onezone &> /dev/null
+
+ACCESS_TOKEN=$(demo-access-token)
+
 RETRY_NUM=0
-while [[ ! -f ${SERVICE_READY_LOCK_FILE} ]]; do
+while ! curl -fk -H "x-auth-token:$ACCESS_TOKEN" -X POST "https://127.0.0.1/api/v3/oneprovider/lookup-file-id/demo-space" &> /dev/null; do
     RETRY_NUM=$((RETRY_NUM + 1))
 
     if ! ((RETRY_NUM % 15)); then
         echo -e "\e[1;33m"
         echo "-------------------------------------------------------------------------"
-        echo "Awaiting Oprovider service readiness..."
+        echo "Awaiting for the demo environment to be set up..."
         echo "-------------------------------------------------------------------------"
         echo -e "\e[0m"
     fi
@@ -21,7 +22,7 @@ while [[ ! -f ${SERVICE_READY_LOCK_FILE} ]]; do
     if [[ ${RETRY_NUM} -eq ${TIMEOUT} ]]; then
         echo -e "\e[1;31m"
         echo "-------------------------------------------------------------------------"
-        echo "ERROR: The Oneprovider service failed to initialize within ${TIMEOUT} seconds, exiting."
+        echo "ERROR: The demo environment failed to be set up within ${TIMEOUT} seconds, exiting."
         echo "-------------------------------------------------------------------------"
         echo -e "\e[0m"
         exit 1
@@ -29,6 +30,5 @@ while [[ ! -f ${SERVICE_READY_LOCK_FILE} ]]; do
 
     sleep 1;
 done
-
 
 exit 0
