VFS-12633 Download and install ones3 in tests

diff --git a/bamboo-specs/bamboo.yml b/bamboo-specs/bamboo.yml
--- a/bamboo-specs/bamboo.yml
+++ b/bamboo-specs/bamboo.yml
@@ -226,6 +226,7 @@ Test provider packages:
         git remote -v
 
         make submodule=bamboos submodules
+        make submodule=oneclient submodules
       description: Init submodules
   - script:
       interpreter: BINSH_OR_CMDEXE
@@ -252,6 +253,27 @@ Test provider packages:
 
         make artifact_cluster_manager artifact_oz_worker
       description: Unpack package artifacts
+  - script:
+      interpreter: BINSH_OR_CMDEXE
+      description: Wait for ones3 package and download it
+      scripts:
+        - |-
+          RELEASE=$(cat RELEASE)
+          ONES3_VERSION=$(git -C oneclient describe --tags --always --abbrev=7 | tr - .)
+          ONES3_PACKAGE_URL="http://packages.devel.onedata.org/apt/ubuntu/${RELEASE}/pool/main/o/ones3/ones3_${ONES3_VERSION}-1~focal_amd64.deb"
+          REPEATS=600
+          until curl --silent --output /dev/null --fail --head $ONES3_PACKAGE_URL
+          do
+            echo "Waiting for ones3 package at: $ONES3_PACKAGE_URL - retries left: $REPEATS"
+            sleep 60
+            REPEATS=$((REPEATS-1))
+            if [ "$REPEATS" -eq "0" ]; then
+              echo "ERROR: Awaiting for ones3 package $ONES3_PACKAGE_URL failed!";
+              exit 1;
+            fi
+          done
+          echo "ones3 package $ONES3_PACKAGE_URL is available - downloading..."
+          wget -P package/focal/binary-amd64/ $ONES3_PACKAGE_URL
   - script:
       interpreter: BINSH_OR_CMDEXE
       scripts:
@@ -358,26 +380,6 @@ Publish dockers:
         git remote -v
         # initialize submodules to get default packages versions
         make submodules
-  - script:
-      interpreter: BINSH_OR_CMDEXE
-      description: Wait for ones3 package
-      scripts:
-      - |-
-        RELEASE=$(cat RELEASE)
-        ONES3_VERSION=$(git -C oneclient describe --tags --always --abbrev=7 | tr - .)
-        ONES3_PACKAGE_URL="http://packages.devel.onedata.org/apt/ubuntu/${RELEASE}/pool/main/o/ones3/ones3_${ONES3_VERSION}-1~focal_amd64.deb"
-        REPEATS=600
-        until curl --silent --output /dev/null --fail --head $ONES3_PACKAGE_URL
-        do
-          echo "Waiting for ones3 package at: $ONES3_PACKAGE_URL - retries left: $REPEATS"
-          sleep 60
-          REPEATS=$((REPEATS-1))
-          if [ "$REPEATS" -eq "0" ]; then
-            echo "ERROR: Awaiting for ones3 package $ONES3_PACKAGE_URL failed!";
-            exit 1;
-          fi
-        done
-        echo "ones3 package $ONES3_PACKAGE_URL is available - continuing..."
   - script:
       interpreter: BINSH_OR_CMDEXE
       scripts:
